### ISSUE TITLE
[S2-PB13] Pengguna dapat mengakses halaman tutorial

### ISSUE THREAD

**Issue by claery** [SI-RPL-2021/SI4208---Nikah-YUK-#11]
Saya sebagai user dapat melihat tutorial sehingga saya dapat mendapatkan tutorial tutorial yang tidak saya ketahui sebelumnya

**Comment by bonylumbanraja** [comment]
Pengguna dapat melihat beberapa tutorial yang diberikan pada halaman tutorial
![Halaman tutorial](https://user-images.githubusercontent.com/71864537/122339936-da8c2500-cf6b-11eb-8781-65ff58e2ac4f.png)
