### ISSUE TITLE
[S1-PBI6] Pengguna dapat mengakses halaman testimoni

### ISSUE THREAD

**Issue by claery** [SI-RPL-2021/SI4208---Nikah-YUK-#13]
Saya sebagai user dapat melihat testimoni sehingga saya sebagai user mendapatkan pendapat dari user lainnya

**Comment by bonylumbanraja** [comment]
Pengguna dapat melihat testimoni dari berbagai pasangan yang telah menggunakan jasa website Nikah-Yuk
![testimoni](https://user-images.githubusercontent.com/71864537/122338672-36ee4500-cf6a-11eb-9436-fdb72fd61230.png)
