### ISSUE TITLE
[S2 - PBI12] Pengguna dapat mengakses dan mengupload berkas pada halaman loker

### ISSUE THREAD

**Issue by feriirawann** [SI-RPL-2021/SI4208---Nikah-YUK-#14]
saya sebagai user bisa menyediakan untuk lowongan kerja

**Comment by bonylumbanraja** [comment]
Pada halaman loker, user dapat memilih lowongan yang diinginkan dan mengupload berkas pendaftaran.

![submit berkas1](https://user-images.githubusercontent.com/71864537/122339833-bcbec000-cf6b-11eb-91d0-321ee50c6498.png)

![Submit berkas](https://user-images.githubusercontent.com/71864537/122339824-baf4fc80-cf6b-11eb-8b4a-95ee236cd8e6.png)
