### ISSUE TITLE
[S1 - PBI3] Pengguna dapat melakukan login dan logout dengan akun yang telah terdaftar

### ISSUE THREAD

**Issue by feriirawann** [SI-RPL-2021/SI4208---Nikah-YUK-#15]
saya sebagai user bisa menampilkan data layanan anggita

**Comment by bonylumbanraja** [comment]
Pada tampilan login, user dapat melakukan login dengan menginputkan email dan password yang sebelumnya telah teregistrasi.
Setelah login user juga dapat melakukan log out dari website.
![Login](https://user-images.githubusercontent.com/71864537/122338348-c7785580-cf69-11eb-82f2-0ab188005158.png)
![Logout](https://user-images.githubusercontent.com/71864537/122338354-c9421900-cf69-11eb-9560-6d8941f856f5.png)
