### ISSUE TITLE
[S1 - PBI5] Pengguna dapat mengakses halaman Blog

### ISSUE THREAD

**Issue by dhanu13** [SI-RPL-2021/SI4208---Nikah-YUK-#2]
saya sebagai user mendapatkan informasi terkait pengalaman pasangan-pasangan sebelumnya yang telah menggunakan layanan ini.

**Comment by bonylumbanraja** [comment]
Pengguna dapat melihat blog mengenai website,vendor, gedung pernikahan dll pada halaman blog.
![Blog](https://user-images.githubusercontent.com/71864537/122338543-10c8a500-cf6a-11eb-9a35-9e14c4f09f1a.png)
