### ISSUE TITLE
[S3 - PBI20] Admin dapat mengakses tampilan dashboard

### ISSUE THREAD

**Issue by ardyrikardo** [SI-RPL-2021/SI4208---Nikah-YUK-#22]

**Comment by bonylumbanraja** [comment]
Pada tampilan dashboard, admin dapat melihat ringkasan data produk, kategori, user dan fitur lainnya yang tersedia pada halaman dashboard
![dashboard](https://user-images.githubusercontent.com/71864537/122340798-ee845680-cf6c-11eb-9a75-94714341e110.png)
