### ISSUE TITLE
[S3 - PBI21] Admin dapat melihat pengguna yang sudah terdaftar di website

### ISSUE THREAD

**Issue by ardyrikardo** [SI-RPL-2021/SI4208---Nikah-YUK-#23]

**Comment by bonylumbanraja** [comment]
Pada tampilan ini, admin dapat melihat pengguna yang telah teregistrasi pada website Nikah-Yuk!
![tampilan pengguna yg sudah daftar di Nikah-YUK!](https://user-images.githubusercontent.com/71864537/122340972-25f30300-cf6d-11eb-898c-7c30f5182893.png)
