### ISSUE TITLE
[S3 - PBI23] Pengguna dapat melihat status progress pada tampilan profile

### ISSUE THREAD

**Issue by ardyrikardo** [SI-RPL-2021/SI4208---Nikah-YUK-#25]

**Comment by bonylumbanraja** [comment]
Pada halaman ini, pengguna dapat melihat order history nya beserta status pemesanan user.
![penggguna melihat status pemesanan](https://user-images.githubusercontent.com/71864537/122341213-6d798f00-cf6d-11eb-8a68-91c9d977395f.png)
