### ISSUE TITLE
[S1 -PBI1] Pengguna melakukan registrasi akun pada website

### ISSUE THREAD

**Issue by claery** [SI-RPL-2021/SI4208---Nikah-YUK-#3]
Saya sebagai user dapat melakukan registrasi sehingga saya dapat login ke nikah yuk

**Comment by bonylumbanraja** [comment]
Pada halaman ini user dapat melakukan registrasi dengan memasukkan nama, email, Phone number, dan password
![regis](https://user-images.githubusercontent.com/71864537/122337804-08bc3580-cf69-11eb-805a-5b0a8c07c074.png)
