### ISSUE TITLE
[S3 - PBI19] Pengguna dapat menambahkan wedding car ke dalam keranjang

### ISSUE THREAD

**Issue by ardyrikardo** [SI-RPL-2021/SI4208---Nikah-YUK-#4]
Saya sebagai user dapat melihat promo

**Comment by bonylumbanraja** [comment]
Salah satu dari kategori layanan yang diberikan adalah wedding car. Pengguna dapat menambahkan wedding car ke dalam cart pada halaman services, dan dapat melihatnya di cart pada tampilan profile.

![details layanan wedding car](https://user-images.githubusercontent.com/71864537/122340722-d6143c00-cf6c-11eb-9261-74222f4f838a.png)
![notif sukses](https://user-images.githubusercontent.com/71864537/122340711-d280b500-cf6c-11eb-8d37-5320c6acc6a9.png)
![tampilan halaman cart pada saat berhasil menambahkan wedding car](https://user-images.githubusercontent.com/71864537/122340718-d44a7880-cf6c-11eb-92ac-bf03e8ef10c6.png)
![Daftar wedding car](https://user-images.githubusercontent.com/71864537/122340719-d4e30f00-cf6c-11eb-9755-4614198cfbb9.png)
