### ISSUE TITLE
[S2 - PBI9] Pengguna dapat mengakses halaman profile

### ISSUE THREAD

**Issue by dhanu13** [SI-RPL-2021/SI4208---Nikah-YUK-#6]
saya sebagai user dapat melihat dan memilih layanan yang tersedia.

**Comment by bonylumbanraja** [comment]
Pada halaman profile, pengguna dapat melihat data pribadi dan fitur didala tampilan profile
![Halaman profile](https://user-images.githubusercontent.com/71864537/122339261-0a86f880-cf6b-11eb-8a0f-b8ef486d6068.png)
