### ISSUE TITLE
[S2 - PBI11] Pengguna dapat melihat halaman keranjang/checkout

### ISSUE THREAD

**Issue by dhanu13** [SI-RPL-2021/SI4208---Nikah-YUK-#8]
saya sebagai user dapat melakukan pendaftaran akun dengan menginput data pada form yang telah disediakan.

**Comment by bonylumbanraja** [comment]
Pengguna dapat melihat layanan yang telah dipilih beserta ringkasan harga pada tampilan cart.
![Halaman Cart](https://user-images.githubusercontent.com/71864537/122339568-76696100-cf6b-11eb-91ae-af4bd4f50722.png)
