### ISSUE TITLE
[S3 - PBI17] Pengguna dapat menambahkan wardrobe ke dalam keranjang

### ISSUE THREAD

**Issue by ardyrikardo** [SI-RPL-2021/SI4208---Nikah-YUK-#9]
Saya sebgai user dapat melihat dashboard dari website Nikah YUK!

**Comment by bonylumbanraja** [comment]
Salah satu dari kategori layanan yang diberikan adalah wardrobe. Pengguna dapat menambahkan wardrobe
 ke dalam cart pada halaman services, dan dapat melihatnya di cart pada tampilan profile.
![setelah produk selesai di tambahkan](https://user-images.githubusercontent.com/71864537/122340525-9188a080-cf6c-11eb-9643-4954766753aa.png)
![Tampilan layanan wardrobe](https://user-images.githubusercontent.com/71864537/122340529-93526400-cf6c-11eb-87ad-a639cc81e8e4.png)
![details produk wardrobe](https://user-images.githubusercontent.com/71864537/122340533-94839100-cf6c-11eb-90c1-7bb4b253cd2c.png)
![notif success](https://user-images.githubusercontent.com/71864537/122340535-951c2780-cf6c-11eb-949b-6da920726e3c.png)
